source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails', '4.2.0'
gem 'pg'
gem 'active_model_serializers'
gem 'raddocs'
gem 'sorcery'

group :production do
  gem 'passenger'
  gem 'heroku-deflater'
  gem 'rails_12factor'
end

group :development, :test do
  gem 'pry'
  gem 'rspec-rails'
  gem 'rspec_api_documentation'
  gem 'database_cleaner'
end

group :development do
  gem 'annotate'
end
